version: '3'

services:
  client:
    build: ./client
    # image: murugi/ip-client:1.0.0
    container_name: react-cloth
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    # build: ./backend
    image: murugi/ip-backend:1.0.0
    container_name: node-api
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - /DevOps/mongo-backup:/data/db
    networks:
      - mern-network
    
networks:
  mern-network:
    driver: bridge




