apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-container
          image: murugi/frontend-ip2:v1.0.1
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"  # Limit the memory to 256 MiB
              cpu: "0.5"       # Limit the CPU to 0.5 cores
            requests:
              memory: "128Mi"  # Request 128 MiB of memory
              cpu: "0.25"      
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
