---
# tasks file for /home/maureen/DevOps/yolo/roles/gitclone
- name: Clone Yolo from GitHub
  git:
        repo: https://github.com/MaureenMurugi/yolo
        dest: ~/DevOps/yolo
        update: yes

- name: Set the working directory to the cloned folder
  command: cd ~/DevOps/yolo
  args:
        chdir: ~/DevOps/yolo
        creates: ~/DevOps/yolo

- name: add userpermissions
  shell: "usermod -aG docker vagrant"

# - name: Run Docker Compose
#   command: docker compose up 
#   args:
#     chdir: ~/DevOps/yolo

- name: Create and start services
  community.docker.docker_compose:
    project_src: ~/DevOps/yolo
  register: output
  